local_costmap:
  global_frame: odom
  robot_base_frame: robot_footprint
  update_frequency: 10.0  # INCREASED for more accurate position tracking
  publish_frequency: 5.0   # INCREASED for smoother visualization
  static_map: false
  rolling_window: true # The map moves with the robot
  width: 4.0
  height: 4.0
  resolution: 0.05
  
  plugins:
    - {name: obstacle_layer,  type: "costmap_2d::ObstacleLayer"}
    - {name: inflation_layer, type: "costmap_2d::InflationLayer"}
