global_costmap:
  global_frame: map
  robot_base_frame: robot_footprint
  update_frequency: 5.0
  publish_frequency: 0.5
  static_map: true # Uses the map provided by map_server
  resolution: 0.05 # Must match the map resolution
  
  plugins:
    - {name: static_layer,    type: "costmap_2d::StaticLayer"}
    - {name: obstacle_layer,  type: "costmap_2d::ObstacleLayer"}
    - {name: inflation_layer, type: "costmap_2d::InflationLayer"}
