shutdown_costmaps: false
controller_frequency: 10.0
planner_patience: 5.0
controller_patience: 15.0
conservative_reset_dist: 3.0
planner_frequency: 5.0
oscillation_timeout: 10.0
oscillation_distance: 0.2

# PLANNERS
# GLOBAL
# base_global_planner: "navfn/NavfnROS" # Dijkstra algorithm for path planning
base_global_planner: "global_planner/GlobalPlanner" # A* algorithm for optimal path planning

# LOCAL
#base_local_planner: "dwa_local_planner/DWAPlannerROS"
base_local_planner: "teb_local_planner/TebLocalPlannerROS" # Timed Elastic Band

# RECOVERY BEHAVIORS
recovery_behavior_enabled: true
recovery_behaviors:
  - name: 'conservative_reset'
    type: 'clear_costmap_recovery/ClearCostmapRecovery'
  - name: 'rotate_recovery'
    type: 'rotate_recovery/RotateRecovery'
  - name: 'aggressive_reset'
    type: 'clear_costmap_recovery/ClearCostmapRecovery'

conservative_reset:
  reset_distance: 3.0

rotate_recovery:
  frequency: 20.0
  sim_granularity: 0.017
  
aggressive_reset:
  reset_distance: 0.0
